### ISSUE TITLE
Re-enabling "build automatically" should be in a finally block 

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/emoflon-core#34] opened 2018-02-21 21:41 UTC
To reproduce:

- Choose a set of projects to build (code generation)
- One of these projects should cause an exception to be thrown (.ecore missing, or properties file corrupt, etc)
- build automatically is switched off at the beginning of the process, but apparently is not switched back on if an exception flies

My only explanation is that switching build automatically back on must be in a try block whereas it should actually be in the finally block to ensure that it is always executed.

**Comment by RolandKluge** [comment] 2018-02-22 08:13
Can you provide me with the exact code location?

**Comment by anthonyanjorin** [comment] 2018-02-22 08:17
If I could I would have fixed it myself :)  I'm just guessing what the problem could be.

**Comment by RolandKluge** [comment] 2018-03-01 10:32
I am currently not able to reproduce this. Do you have a sample project for me?

* If I rename moflon.properties.xmi, it is recreated.
* If the .ecore file is missing, nothing happens at all.

As far as I know, the JDT may also switch off autobuild if it thinks that an infinite build circle may arise.

Also, as far as I know, eMoflon Core only manipulates the autobuild behavior via this class, which is only used by the WorkspaceInstaller: org.moflon.core.build.TaskUtilities .

**Comment by RolandKluge** [comment] 2018-03-02 13:52
I close this issue for now.

Let's reopen it, if there is a concrete project for reproduction

**Closed by RolandKluge** 2018-03-02 13:52 UTC
